server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          name: attrs.containerPrettyName
    - json:
        expressions:
          tag:
        source: attrs
    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: tag
    - timestamp:
        format: RFC3339Nano
        source: time
    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id:
        name:
    - output:
        source: output


  - job_name: manual_fixes
    static_configs:
    - targets:
        - localhost
      labels:
        job: manual_fixes_logs
        __path__: /manual_fixes.log

    pipeline_stages:
    - json:
        expressions:
          fixed_by: fixed_by
          fixes: fixes
          description: description
    - timestamp:
        format: RFC3339Nano
        source: time
    - labels:
        fixed_by:
        fixes:
        description:
    - output:
        source: description
